#!/bin/bash

./clean_language_reverse.sh	afrikaans	
./clean_language_reverse.sh	amharic	
./clean_language_reverse.sh	arabic	
./clean_language_reverse.sh	armenian	
./clean_language_reverse.sh	azerbaijani	
./clean_language_reverse.sh	basque	
./clean_language_reverse.sh	belarusian	
./clean_language_reverse.sh	bengali	
./clean_language_reverse.sh	bengali/dhaka	
./clean_language_reverse.sh	bengali/rahr	
./clean_language_reverse.sh	bulgarian	
./clean_language_reverse.sh	burmese	
./clean_language_reverse.sh	catalan	
./clean_language_reverse.sh	cebuano	
./clean_language_reverse.sh	chechen	
./clean_language_reverse.sh	chichewa	
./clean_language_reverse.sh	chinese/mandarin	-padspace
./clean_language_reverse.sh	croatian	
./clean_language_reverse.sh	czech	
./clean_language_reverse.sh	danish	
./clean_language_reverse.sh	dutch	
./clean_language_reverse.sh	dzongkha	
./clean_language_reverse.sh	english	
./clean_language_reverse.sh	esperanto	
./clean_language_reverse.sh	estonian	
./clean_language_reverse.sh	farsi	
./clean_language_reverse.sh	finnish	
./clean_language_reverse.sh	french	
./clean_language_reverse.sh	galician	
./clean_language_reverse.sh	georgian	
./clean_language_reverse.sh	german	
./clean_language_reverse.sh	greek	
./clean_language_reverse.sh	gujarati	
./clean_language_reverse.sh	hausa	
./clean_language_reverse.sh	hebrew	
./clean_language_reverse.sh	hindi	
./clean_language_reverse.sh	hungarian	
./clean_language_reverse.sh	icelandic	
./clean_language_reverse.sh	indonesian	
./clean_language_reverse.sh	isan	
./clean_language_reverse.sh	italian	
./clean_language_reverse.sh	jamaican	
./clean_language_reverse.sh	japanese	-padspace
./clean_language_reverse.sh	javanese	
./clean_language_reverse.sh	kazakh	
./clean_language_reverse.sh	khmer/central	
./clean_language_reverse.sh	korean	
./clean_language_reverse.sh	lao	
./clean_language_reverse.sh	latvian	
./clean_language_reverse.sh	lithuanian	
./clean_language_reverse.sh	luxembourgish	
./clean_language_reverse.sh	macedonian	
./clean_language_reverse.sh	malay/arab	
./clean_language_reverse.sh	malay/latin	
./clean_language_reverse.sh	malayalam	
./clean_language_reverse.sh	maltese	
./clean_language_reverse.sh	marathi	
./clean_language_reverse.sh	mongolian	
./clean_language_reverse.sh	nepali	
./clean_language_reverse.sh	norwegian	
./clean_language_reverse.sh	pashto	
./clean_language_reverse.sh	polish	
./clean_language_reverse.sh	portuguese	
./clean_language_reverse.sh	punjabi	
./clean_language_reverse.sh	romanian	
./clean_language_reverse.sh	russian	
./clean_language_reverse.sh	serbian	
./clean_language_reverse.sh	slovak	
./clean_language_reverse.sh	spanish	
./clean_language_reverse.sh	swahili	
./clean_language_reverse.sh	swedish	
./clean_language_reverse.sh	tagalog	
./clean_language_reverse.sh	tamil	
./clean_language_reverse.sh	telugu	
./clean_language_reverse.sh	thai	
./clean_language_reverse.sh	tibetan	-padspace
./clean_language_reverse.sh	turkish	
./clean_language_reverse.sh	ukrainian	
./clean_language_reverse.sh	urdu	
./clean_language_reverse.sh	uyghur	
./clean_language_reverse.sh	vietnamese/central	
./clean_language_reverse.sh	vietnamese/northern	
./clean_language_reverse.sh	vietnamese/southern	
./clean_language_reverse.sh	yoruba	
./clean_language_reverse.sh	zulu	

