#!/bin/bash
./clean_language_reverse.sh     cantonese -padspace
./clean_language_reverse.sh     minnan/hokkien -padspace
./clean_language_reverse.sh     minnan/taiwanese -padspace
./clean_language_reverse.sh	hebrew2
exit
./clean_language_reverse.sh	albanian	
./clean_language_reverse.sh	aragonese	
./clean_language_reverse.sh	assamese	
./clean_language_reverse.sh	bashkir	
./clean_language_reverse.sh	bishnupriyamanipuri	
./clean_language_reverse.sh	bosnian	
./clean_language_reverse.sh	cherokee	
./clean_language_reverse.sh	chuvash	
./clean_language_reverse.sh	gaelic/irish	
./clean_language_reverse.sh	gaelic/scottish	
./clean_language_reverse.sh	greenlandic	
./clean_language_reverse.sh	guarani	
./clean_language_reverse.sh	haitiancreole	
./clean_language_reverse.sh	hawaiian	
./clean_language_reverse.sh	ido	
./clean_language_reverse.sh	interlingua	
./clean_language_reverse.sh	kannada	
./clean_language_reverse.sh	kiche	
./clean_language_reverse.sh	konkani	
./clean_language_reverse.sh	kurdish	
./clean_language_reverse.sh	kyrgyz	
./clean_language_reverse.sh	langbelta	
./clean_language_reverse.sh	latgalian	
./clean_language_reverse.sh	latin/classical	
./clean_language_reverse.sh	latin/ecclesiastical	
./clean_language_reverse.sh	linguafrancanova	
./clean_language_reverse.sh	lojban	
./clean_language_reverse.sh	lulesaami	
./clean_language_reverse.sh	maori	
./clean_language_reverse.sh	nahuatl/central	
./clean_language_reverse.sh	nahuatl/classical	
./clean_language_reverse.sh	nahuatl/mecayapan	
./clean_language_reverse.sh	nahuatl/tetelcingo	
./clean_language_reverse.sh	nogai	
./clean_language_reverse.sh	oromo	
./clean_language_reverse.sh	papiamento	
./clean_language_reverse.sh	quechua	
./clean_language_reverse.sh	quenya	
./clean_language_reverse.sh	setswana	
./clean_language_reverse.sh	shantaiyai	
./clean_language_reverse.sh	sindarin	
./clean_language_reverse.sh	sindhi	
./clean_language_reverse.sh	sinhala	
./clean_language_reverse.sh	slovenian	
./clean_language_reverse.sh	tatar	
./clean_language_reverse.sh	turkmen	
./clean_language_reverse.sh	uzbek	
./clean_language_reverse.sh	welsh/north	
./clean_language_reverse.sh	welsh/south
./clean_language_reverse.sh	afrikaans	
./clean_language_reverse.sh	amharic	
./clean_language_reverse.sh	arabic	
./clean_language_reverse.sh	armenian	
./clean_language_reverse.sh	azerbaijani	
./clean_language_reverse.sh	basque	
./clean_language_reverse.sh	belarusian	
./clean_language_reverse.sh	bengali	
./clean_language_reverse.sh	bengali/dhaka	
./clean_language_reverse.sh	bengali/rahr	
./clean_language_reverse.sh	bulgarian	
./clean_language_reverse.sh	burmese	
./clean_language_reverse.sh	catalan	
./clean_language_reverse.sh	cebuano	
./clean_language_reverse.sh	chechen	
./clean_language_reverse.sh	chichewa	
./clean_language_reverse.sh	chinese/mandarin	-padspace
./clean_language_reverse.sh	croatian	
./clean_language_reverse.sh	czech	
./clean_language_reverse.sh	danish	
./clean_language_reverse.sh	dutch	
./clean_language_reverse.sh	dzongkha	
./clean_language_reverse.sh	english	
./clean_language_reverse.sh	esperanto	
./clean_language_reverse.sh	estonian	
./clean_language_reverse.sh	farsi	
./clean_language_reverse.sh	finnish	
./clean_language_reverse.sh	french	
./clean_language_reverse.sh	galician	
./clean_language_reverse.sh	georgian	
./clean_language_reverse.sh	german	
./clean_language_reverse.sh	greek	
./clean_language_reverse.sh	gujarati	
./clean_language_reverse.sh	hausa	
./clean_language_reverse.sh	hebrew	
./clean_language_reverse.sh	hindi	
./clean_language_reverse.sh	hungarian	
./clean_language_reverse.sh	icelandic	
./clean_language_reverse.sh	indonesian	
./clean_language_reverse.sh	isan	
./clean_language_reverse.sh	italian	
./clean_language_reverse.sh	jamaican	
./clean_language_reverse.sh	japanese	-padspace
./clean_language_reverse.sh	javanese	
./clean_language_reverse.sh	kazakh	
./clean_language_reverse.sh	khmer/central	
./clean_language_reverse.sh	korean	
./clean_language_reverse.sh	lao	
./clean_language_reverse.sh	latvian	
./clean_language_reverse.sh	lithuanian	
./clean_language_reverse.sh	luxembourgish	
./clean_language_reverse.sh	macedonian	
./clean_language_reverse.sh	malay/arab	
./clean_language_reverse.sh	malay/latin	
./clean_language_reverse.sh	malayalam	
./clean_language_reverse.sh	maltese	
./clean_language_reverse.sh	marathi	
./clean_language_reverse.sh	mongolian	
./clean_language_reverse.sh	nepali	
./clean_language_reverse.sh	norwegian	
./clean_language_reverse.sh	pashto	
./clean_language_reverse.sh	polish	
./clean_language_reverse.sh	portuguese	
./clean_language_reverse.sh	punjabi	
./clean_language_reverse.sh	romanian	
./clean_language_reverse.sh	russian	
./clean_language_reverse.sh	serbian	
./clean_language_reverse.sh	slovak	
./clean_language_reverse.sh	spanish	
./clean_language_reverse.sh	swahili	
./clean_language_reverse.sh	swedish	
./clean_language_reverse.sh	tagalog	
./clean_language_reverse.sh	tamil	
./clean_language_reverse.sh	telugu	
./clean_language_reverse.sh	thai	
./clean_language_reverse.sh	tibetan	-padspace
./clean_language_reverse.sh	turkish	
./clean_language_reverse.sh	ukrainian	
./clean_language_reverse.sh	urdu	
./clean_language_reverse.sh	uyghur	
./clean_language_reverse.sh	vietnamese/central	
./clean_language_reverse.sh	vietnamese/northern	
./clean_language_reverse.sh	vietnamese/southern	
./clean_language_reverse.sh	yoruba	
./clean_language_reverse.sh	zulu	
