#!/bin/bash

SENTENCES="/home/m/go/src/example.com/repo.git/"

./hyper_parameter_evaluate.sh afrikaans $SENTENCES/low-quality-multilingual-sentences/af.jsonl.zst
./hyper_parameter_evaluate.sh albanian $SENTENCES/high-quality-multilingual-sentences/sq.jsonl.zst
./hyper_parameter_evaluate.sh amharic $SENTENCES/low-quality-multilingual-sentences/am.jsonl.zst
./hyper_parameter_evaluate.sh arabic $SENTENCES/high-quality-multilingual-sentences/ar.jsonl.zst
./hyper_parameter_evaluate.sh aragonese $SENTENCES/low-quality-multilingual-sentences/an.jsonl.zst
./hyper_parameter_evaluate.sh armenian $SENTENCES/high-quality-multilingual-sentences/hy.jsonl.zst
./hyper_parameter_evaluate.sh assamese $SENTENCES/low-quality-multilingual-sentences/as.jsonl.zst
./hyper_parameter_evaluate.sh azerbaijani $SENTENCES/high-quality-multilingual-sentences/az.jsonl.zst
./hyper_parameter_evaluate.sh bashkir $SENTENCES/low-quality-multilingual-sentences/ba.jsonl.zst
./hyper_parameter_evaluate.sh basque $SENTENCES/low-quality-multilingual-sentences/eu.jsonl.zst
./hyper_parameter_evaluate.sh belarusian $SENTENCES/low-quality-multilingual-sentences/be.jsonl.zst
./hyper_parameter_evaluate.sh bengali/dhaka $SENTENCES/high-quality-multilingual-sentences/bn.jsonl.zst
./hyper_parameter_evaluate.sh bengali $SENTENCES/high-quality-multilingual-sentences/bn.jsonl.zst
./hyper_parameter_evaluate.sh bengali/rahr $SENTENCES/high-quality-multilingual-sentences/bn.jsonl.zst
./hyper_parameter_evaluate.sh bishnupriyamanipuri $SENTENCES/low-quality-multilingual-sentences/bpy.jsonl.zst
./hyper_parameter_evaluate.sh bosnian $SENTENCES/low-quality-multilingual-sentences/bs.jsonl.zst
./hyper_parameter_evaluate.sh bulgarian $SENTENCES/high-quality-multilingual-sentences/bg.jsonl.zst
./hyper_parameter_evaluate.sh burmese $SENTENCES/low-quality-multilingual-sentences/my.jsonl.zst
./hyper_parameter_evaluate.sh cantonese $SENTENCES/low-quality-multilingual-sentences/yue.jsonl.zst
./hyper_parameter_evaluate.sh catalan $SENTENCES/high-quality-multilingual-sentences/ca.jsonl.zst
./hyper_parameter_evaluate.sh cebuano $SENTENCES/low-quality-multilingual-sentences/ceb.jsonl.zst
./hyper_parameter_evaluate.sh chechen $SENTENCES/low-quality-multilingual-sentences/ce.jsonl.zst
./hyper_parameter_evaluate.sh cherokee $SENTENCES/low-quality-multilingual-sentences/chr.jsonl.zst
./hyper_parameter_evaluate.sh chichewa $SENTENCES/low-quality-multilingual-sentences/ny.jsonl.zst
./hyper_parameter_evaluate.sh chinese/mandarin $SENTENCES/high-quality-multilingual-sentences/zh.jsonl.zst
./hyper_parameter_evaluate.sh chuvash $SENTENCES/low-quality-multilingual-sentences/cv.jsonl.zst
./hyper_parameter_evaluate.sh croatian $SENTENCES/low-quality-multilingual-sentences/hr.jsonl.zst
./hyper_parameter_evaluate.sh czech $SENTENCES/high-quality-multilingual-sentences/cs.jsonl.zst
./hyper_parameter_evaluate.sh danish $SENTENCES/high-quality-multilingual-sentences/da.jsonl.zst
./hyper_parameter_evaluate.sh dutch $SENTENCES/high-quality-multilingual-sentences/nl.jsonl.zst
./hyper_parameter_evaluate.sh dzongkha $SENTENCES/low-quality-multilingual-sentences/dz.jsonl.zst
./hyper_parameter_evaluate.sh english/american $SENTENCES/high-quality-multilingual-sentences/en.jsonl.zst
./hyper_parameter_evaluate.sh english/british $SENTENCES/high-quality-multilingual-sentences/en.jsonl.zst
./hyper_parameter_evaluate.sh english $SENTENCES/high-quality-multilingual-sentences/en.jsonl.zst
./hyper_parameter_evaluate.sh esperanto $SENTENCES/low-quality-multilingual-sentences/eo.jsonl.zst
./hyper_parameter_evaluate.sh estonian $SENTENCES/high-quality-multilingual-sentences/et.jsonl.zst
./hyper_parameter_evaluate.sh farsi $SENTENCES/high-quality-multilingual-sentences/fa.jsonl.zst
./hyper_parameter_evaluate.sh finnish $SENTENCES/high-quality-multilingual-sentences/fi.jsonl.zst
./hyper_parameter_evaluate.sh french $SENTENCES/high-quality-multilingual-sentences/fr.jsonl.zst
./hyper_parameter_evaluate.sh gaelic/irish $SENTENCES/low-quality-multilingual-sentences/ga.jsonl.zst
./hyper_parameter_evaluate.sh gaelic/scottish $SENTENCES/low-quality-multilingual-sentences/gd.jsonl.zst
./hyper_parameter_evaluate.sh galician $SENTENCES/low-quality-multilingual-sentences/gl.jsonl.zst
./hyper_parameter_evaluate.sh georgian $SENTENCES/high-quality-multilingual-sentences/ka.jsonl.zst
./hyper_parameter_evaluate.sh german $SENTENCES/high-quality-multilingual-sentences/de.jsonl.zst
./hyper_parameter_evaluate.sh greek $SENTENCES/high-quality-multilingual-sentences/el.jsonl.zst
./hyper_parameter_evaluate.sh greenlandic $SENTENCES/low-quality-multilingual-sentences/kl.jsonl.zst
./hyper_parameter_evaluate.sh guarani $SENTENCES/low-quality-multilingual-sentences/gn.jsonl.zst
./hyper_parameter_evaluate.sh gujarati $SENTENCES/low-quality-multilingual-sentences/gu.jsonl.zst
./hyper_parameter_evaluate.sh haitiancreole $SENTENCES/low-quality-multilingual-sentences/ht.jsonl.zst
./hyper_parameter_evaluate.sh hausa $SENTENCES/low-quality-multilingual-sentences/ha.jsonl.zst
./hyper_parameter_evaluate.sh hawaiian $SENTENCES/low-quality-multilingual-sentences/haw.jsonl.zst
./hyper_parameter_evaluate.sh hebrew2 $SENTENCES/low-quality-multilingual-sentences/he_nikud.jsonl.zst
./hyper_parameter_evaluate.sh hebrew3 $SENTENCES/high-quality-multilingual-sentences/he.jsonl.zst
./hyper_parameter_evaluate.sh hindi $SENTENCES/high-quality-multilingual-sentences/hi.jsonl.zst
./hyper_parameter_evaluate.sh hungarian $SENTENCES/high-quality-multilingual-sentences/hu.jsonl.zst
./hyper_parameter_evaluate.sh icelandic $SENTENCES/high-quality-multilingual-sentences/is.jsonl.zst
./hyper_parameter_evaluate.sh ido $SENTENCES/low-quality-multilingual-sentences/io.jsonl.zst
./hyper_parameter_evaluate.sh indonesian $SENTENCES/high-quality-multilingual-sentences/id.jsonl.zst
./hyper_parameter_evaluate.sh interlingua $SENTENCES/low-quality-multilingual-sentences/ia.jsonl.zst
./hyper_parameter_evaluate.sh isan $SENTENCES/low-quality-multilingual-sentences/tts.jsonl.zst
./hyper_parameter_evaluate.sh italian $SENTENCES/high-quality-multilingual-sentences/it.jsonl.zst
./hyper_parameter_evaluate.sh jamaican $SENTENCES/low-quality-multilingual-sentences/jam.jsonl.zst
./hyper_parameter_evaluate.sh japanese $SENTENCES/high-quality-multilingual-sentences/ja.jsonl.zst
./hyper_parameter_evaluate.sh javanese $SENTENCES/low-quality-multilingual-sentences/jv.jsonl.zst
./hyper_parameter_evaluate.sh kannada $SENTENCES/low-quality-multilingual-sentences/kn.jsonl.zst
./hyper_parameter_evaluate.sh kazakh $SENTENCES/high-quality-multilingual-sentences/kk.jsonl.zst
./hyper_parameter_evaluate.sh khmer/central $SENTENCES/low-quality-multilingual-sentences/km.jsonl.zst
./hyper_parameter_evaluate.sh kiche $SENTENCES/low-quality-multilingual-sentences/quc.jsonl.zst
./hyper_parameter_evaluate.sh konkani $SENTENCES/low-quality-multilingual-sentences/kok.jsonl.zst
./hyper_parameter_evaluate.sh korean $SENTENCES/high-quality-multilingual-sentences/ko.jsonl.zst
./hyper_parameter_evaluate.sh kurdish $SENTENCES/low-quality-multilingual-sentences/ku.jsonl.zst
./hyper_parameter_evaluate.sh kyrgyz $SENTENCES/low-quality-multilingual-sentences/ky.jsonl.zst
./hyper_parameter_evaluate.sh langbelta $SENTENCES/low-quality-multilingual-sentences/langbelta.jsonl.zst
./hyper_parameter_evaluate.sh lao $SENTENCES/low-quality-multilingual-sentences/lo.jsonl.zst
./hyper_parameter_evaluate.sh latgalian $SENTENCES/low-quality-multilingual-sentences/ltg.jsonl.zst
./hyper_parameter_evaluate.sh latin/classical $SENTENCES/low-quality-multilingual-sentences/la_classical.jsonl.zst
./hyper_parameter_evaluate.sh latin/ecclesiastical $SENTENCES/low-quality-multilingual-sentences/la_ecclesiastical.jsonl.zst
./hyper_parameter_evaluate.sh latvian $SENTENCES/high-quality-multilingual-sentences/lv.jsonl.zst
./hyper_parameter_evaluate.sh linguafrancanova $SENTENCES/low-quality-multilingual-sentences/lfn.jsonl.zst
./hyper_parameter_evaluate.sh lithuanian $SENTENCES/high-quality-multilingual-sentences/lt.jsonl.zst
./hyper_parameter_evaluate.sh lojban $SENTENCES/low-quality-multilingual-sentences/jbo.jsonl.zst
./hyper_parameter_evaluate.sh lulesaami $SENTENCES/low-quality-multilingual-sentences/smj.jsonl.zst
./hyper_parameter_evaluate.sh luxembourgish $SENTENCES/low-quality-multilingual-sentences/lb.jsonl.zst
./hyper_parameter_evaluate.sh macedonian $SENTENCES/high-quality-multilingual-sentences/mk.jsonl.zst
./hyper_parameter_evaluate.sh malayalam $SENTENCES/high-quality-multilingual-sentences/ml.jsonl.zst
./hyper_parameter_evaluate.sh malay/arab $SENTENCES/low-quality-multilingual-sentences/ms_arab.jsonl.zst
./hyper_parameter_evaluate.sh malay/latin $SENTENCES/high-quality-multilingual-sentences/ms.jsonl.zst
./hyper_parameter_evaluate.sh maltese $SENTENCES/low-quality-multilingual-sentences/mt.jsonl.zst
./hyper_parameter_evaluate.sh maori $SENTENCES/low-quality-multilingual-sentences/mi.jsonl.zst
./hyper_parameter_evaluate.sh marathi $SENTENCES/high-quality-multilingual-sentences/mr.jsonl.zst
./hyper_parameter_evaluate.sh minnan/hokkien2 $SENTENCES/low-quality-multilingual-sentences/nan.jsonl.zst
./hyper_parameter_evaluate.sh minnan/taiwanese2 $SENTENCES/low-quality-multilingual-sentences/nan.jsonl.zst
./hyper_parameter_evaluate.sh mongolian $SENTENCES/low-quality-multilingual-sentences/mn.jsonl.zst
./hyper_parameter_evaluate.sh nahuatl/central $SENTENCES/low-quality-multilingual-sentences/nah.jsonl.zst
./hyper_parameter_evaluate.sh nahuatl/classical $SENTENCES/low-quality-multilingual-sentences/nci.jsonl.zst
./hyper_parameter_evaluate.sh nahuatl/mecayapan $SENTENCES/low-quality-multilingual-sentences/nhx.jsonl.zst
./hyper_parameter_evaluate.sh nahuatl/tetelcingo $SENTENCES/low-quality-multilingual-sentences/nhg.jsonl.zst
./hyper_parameter_evaluate.sh nepali $SENTENCES/high-quality-multilingual-sentences/ne.jsonl.zst
./hyper_parameter_evaluate.sh nogai $SENTENCES/low-quality-multilingual-sentences/nog.jsonl.zst
./hyper_parameter_evaluate.sh norwegian $SENTENCES/high-quality-multilingual-sentences/no.jsonl.zst
./hyper_parameter_evaluate.sh oromo $SENTENCES/low-quality-multilingual-sentences/om.jsonl.zst
./hyper_parameter_evaluate.sh papiamento $SENTENCES/low-quality-multilingual-sentences/pap.jsonl.zst
./hyper_parameter_evaluate.sh pashto $SENTENCES/low-quality-multilingual-sentences/ps.jsonl.zst
./hyper_parameter_evaluate.sh polish $SENTENCES/high-quality-multilingual-sentences/pl.jsonl.zst
./hyper_parameter_evaluate.sh portuguese $SENTENCES/high-quality-multilingual-sentences/pt.jsonl.zst
./hyper_parameter_evaluate.sh punjabi $SENTENCES/low-quality-multilingual-sentences/pa.jsonl.zst
./hyper_parameter_evaluate.sh quechua $SENTENCES/low-quality-multilingual-sentences/qu.jsonl.zst
./hyper_parameter_evaluate.sh quenya $SENTENCES/low-quality-multilingual-sentences/quenya.jsonl.zst
./hyper_parameter_evaluate.sh romanian $SENTENCES/high-quality-multilingual-sentences/ro.jsonl.zst
./hyper_parameter_evaluate.sh russian $SENTENCES/high-quality-multilingual-sentences/ru.jsonl.zst
./hyper_parameter_evaluate.sh serbian $SENTENCES/high-quality-multilingual-sentences/sr.jsonl.zst
./hyper_parameter_evaluate.sh setswana $SENTENCES/low-quality-multilingual-sentences/tn.jsonl.zst
./hyper_parameter_evaluate.sh shantaiyai $SENTENCES/low-quality-multilingual-sentences/shantaiyai.jsonl.zst
./hyper_parameter_evaluate.sh sindarin $SENTENCES/low-quality-multilingual-sentences/sindarin.jsonl.zst
./hyper_parameter_evaluate.sh sindhi $SENTENCES/low-quality-multilingual-sentences/sd.jsonl.zst
./hyper_parameter_evaluate.sh sinhala $SENTENCES/low-quality-multilingual-sentences/si.jsonl.zst
./hyper_parameter_evaluate.sh slovak $SENTENCES/high-quality-multilingual-sentences/sk.jsonl.zst
./hyper_parameter_evaluate.sh slovenian $SENTENCES/high-quality-multilingual-sentences/sl.jsonl.zst
./hyper_parameter_evaluate.sh spanish $SENTENCES/high-quality-multilingual-sentences/es.jsonl.zst
./hyper_parameter_evaluate.sh swahili $SENTENCES/low-quality-multilingual-sentences/sw.jsonl.zst
./hyper_parameter_evaluate.sh swedish $SENTENCES/high-quality-multilingual-sentences/sv.jsonl.zst
./hyper_parameter_evaluate.sh tagalog $SENTENCES/low-quality-multilingual-sentences/tl.jsonl.zst
./hyper_parameter_evaluate.sh tamil $SENTENCES/high-quality-multilingual-sentences/ta.jsonl.zst
./hyper_parameter_evaluate.sh tatar $SENTENCES/low-quality-multilingual-sentences/tt.jsonl.zst
./hyper_parameter_evaluate.sh telugu $SENTENCES/low-quality-multilingual-sentences/te.jsonl.zst
./hyper_parameter_evaluate.sh thai $SENTENCES/high-quality-multilingual-sentences/th.jsonl.zst
./hyper_parameter_evaluate.sh tibetan $SENTENCES/low-quality-multilingual-sentences/bo.jsonl.zst
./hyper_parameter_evaluate.sh turkish $SENTENCES/high-quality-multilingual-sentences/tr.jsonl.zst
./hyper_parameter_evaluate.sh turkmen $SENTENCES/low-quality-multilingual-sentences/tk.jsonl.zst
./hyper_parameter_evaluate.sh ukrainian $SENTENCES/high-quality-multilingual-sentences/uk.jsonl.zst
./hyper_parameter_evaluate.sh urdu $SENTENCES/high-quality-multilingual-sentences/ur.jsonl.zst
./hyper_parameter_evaluate.sh uyghur $SENTENCES/low-quality-multilingual-sentences/ug.jsonl.zst
./hyper_parameter_evaluate.sh uzbek $SENTENCES/low-quality-multilingual-sentences/uz.jsonl.zst
./hyper_parameter_evaluate.sh vietnamese/central $SENTENCES/high-quality-multilingual-sentences/vi.jsonl.zst
./hyper_parameter_evaluate.sh vietnamese/northern $SENTENCES/high-quality-multilingual-sentences/vi.jsonl.zst
./hyper_parameter_evaluate.sh vietnamese/southern $SENTENCES/high-quality-multilingual-sentences/vi.jsonl.zst
./hyper_parameter_evaluate.sh welsh/north $SENTENCES/low-quality-multilingual-sentences/cy_north.jsonl.zst
./hyper_parameter_evaluate.sh welsh/south $SENTENCES/low-quality-multilingual-sentences/cy_south.jsonl.zst
./hyper_parameter_evaluate.sh yoruba $SENTENCES/low-quality-multilingual-sentences/yo.jsonl.zst
./hyper_parameter_evaluate.sh zulu $SENTENCES/low-quality-multilingual-sentences/zu.jsonl.zst

