#!/bin/bash

./study_language_reverse.sh	afrikaans  --rowlossimportance 5
./study_language_reverse.sh	albanian  --rowlossimportance 2
./study_language_reverse.sh	amharic  --rowlossimportance 1
./study_language_reverse.sh	arabic  --rowlossimportance 2
./study_language_reverse.sh	aragonese  --rowlossimportance 10
./study_language_reverse.sh	armenian  --rowlossimportance 1
./study_language_reverse.sh	assamese  --rowlossimportance 8
./study_language_reverse.sh	azerbaijani  --rowlossimportance 4
./study_language_reverse.sh	bashkir  --rowlossimportance 1
./study_language_reverse.sh	basque  --rowlossimportance 1
./study_language_reverse.sh	belarusian  --rowlossimportance 5
./study_language_reverse.sh	bengali  --rowlossimportance 8
./study_language_reverse.sh	bishnupriyamanipuri  --rowlossimportance 0
./study_language_reverse.sh	bosnian  --rowlossimportance 7
./study_language_reverse.sh	bulgarian  --rowlossimportance 3
./study_language_reverse.sh	burmese  --rowlossimportance 0
./study_language_reverse.sh	cantonese -padspace  --rowlossimportance 0
./study_language_reverse.sh	catalan  --rowlossimportance 2
./study_language_reverse.sh	cebuano  --rowlossimportance 0
./study_language_reverse.sh	chechen  --rowlossimportance 6
./study_language_reverse.sh	cherokee  --rowlossimportance 0
./study_language_reverse.sh	chichewa  --rowlossimportance 8
./study_language_reverse.sh	chuvash  --rowlossimportance 1
./study_language_reverse.sh	croatian  --rowlossimportance 6
./study_language_reverse.sh	czech  --rowlossimportance 1
./study_language_reverse.sh	danish  --rowlossimportance 1
./study_language_reverse.sh	dutch  --rowlossimportance 4
./study_language_reverse.sh	dzongkha  --rowlossimportance 0
./study_language_reverse.sh	english  --rowlossimportance 2
./study_language_reverse.sh	esperanto  --rowlossimportance 3
./study_language_reverse.sh	estonian  --rowlossimportance 1
./study_language_reverse.sh	farsi  --rowlossimportance 6
./study_language_reverse.sh	finnish  --rowlossimportance 8
./study_language_reverse.sh	french  --rowlossimportance 4
./study_language_reverse.sh	galician  --rowlossimportance 9
./study_language_reverse.sh	georgian  --rowlossimportance 10
./study_language_reverse.sh	german  --rowlossimportance 4
./study_language_reverse.sh	greek  --rowlossimportance 6
./study_language_reverse.sh	greenlandic  --rowlossimportance 1
./study_language_reverse.sh	guarani  --rowlossimportance 9
./study_language_reverse.sh	gujarati  --rowlossimportance 10
./study_language_reverse.sh	haitiancreole  --rowlossimportance 0
./study_language_reverse.sh	hausa  --rowlossimportance 6
./study_language_reverse.sh	hawaiian  --rowlossimportance 0
./study_language_reverse.sh	hebrew2  --rowlossimportance 10
./study_language_reverse.sh	hebrew3  --rowlossimportance 1
./study_language_reverse.sh	hindi  --rowlossimportance 2
./study_language_reverse.sh	hungarian  --rowlossimportance 5
./study_language_reverse.sh	icelandic  --rowlossimportance 0
./study_language_reverse.sh	ido  --rowlossimportance 1
./study_language_reverse.sh	indonesian  --rowlossimportance 2
./study_language_reverse.sh	interlingua  --rowlossimportance 7
./study_language_reverse.sh	isan  --rowlossimportance 10
./study_language_reverse.sh	italian  --rowlossimportance 10
./study_language_reverse.sh	jamaican  --rowlossimportance 10
./study_language_reverse.sh	japanese -padspace  --rowlossimportance 10
./study_language_reverse.sh	javanese  --rowlossimportance 10
./study_language_reverse.sh	kannada  --rowlossimportance 10
./study_language_reverse.sh	kazakh  --rowlossimportance 10
./study_language_reverse.sh	kiche  --rowlossimportance 10
./study_language_reverse.sh	konkani  --rowlossimportance 10
./study_language_reverse.sh	korean  --rowlossimportance 10
./study_language_reverse.sh	kurdish  --rowlossimportance 10
./study_language_reverse.sh	kyrgyz  --rowlossimportance 10
./study_language_reverse.sh	langbelta  --rowlossimportance 10
./study_language_reverse.sh	lao  --rowlossimportance 10
./study_language_reverse.sh	latgalian  --rowlossimportance 10
./study_language_reverse.sh	latvian  --rowlossimportance 10
./study_language_reverse.sh	linguafrancanova  --rowlossimportance 10
./study_language_reverse.sh	lithuanian  --rowlossimportance 10
./study_language_reverse.sh	lojban  --rowlossimportance 10
./study_language_reverse.sh	lulesaami  --rowlossimportance 10
./study_language_reverse.sh	luxembourgish  --rowlossimportance 10
./study_language_reverse.sh	macedonian  --rowlossimportance 10
./study_language_reverse.sh	malayalam  --rowlossimportance 2
./study_language_reverse.sh	maltese  --rowlossimportance 10
./study_language_reverse.sh	maori  --rowlossimportance 10
./study_language_reverse.sh	marathi  --rowlossimportance 10
./study_language_reverse.sh	mongolian  --rowlossimportance 10
./study_language_reverse.sh	nepali  --rowlossimportance 10
./study_language_reverse.sh	nogai  --rowlossimportance 10
./study_language_reverse.sh	norwegian  --rowlossimportance 10
./study_language_reverse.sh	oromo  --rowlossimportance 10
./study_language_reverse.sh	papiamento  --rowlossimportance 10
./study_language_reverse.sh	pashto  --rowlossimportance 10
./study_language_reverse.sh	polish  --rowlossimportance 10
./study_language_reverse.sh	portuguese  --rowlossimportance 10
./study_language_reverse.sh	punjabi  --rowlossimportance 10
./study_language_reverse.sh	quechua  --rowlossimportance 10
./study_language_reverse.sh	quenya  --rowlossimportance 10
./study_language_reverse.sh	romanian  --rowlossimportance 10
./study_language_reverse.sh	russian  --rowlossimportance 10
./study_language_reverse.sh	serbian  --rowlossimportance 10
./study_language_reverse.sh	setswana  --rowlossimportance 10
./study_language_reverse.sh	shantaiyai -padspace  --rowlossimportance 10
./study_language_reverse.sh	sindarin  --rowlossimportance 10
./study_language_reverse.sh	sindhi  --rowlossimportance 10
./study_language_reverse.sh	sinhala  --rowlossimportance 10
./study_language_reverse.sh	slovak  --rowlossimportance 7
./study_language_reverse.sh	slovenian  --rowlossimportance 10
./study_language_reverse.sh	spanish  --rowlossimportance 10
./study_language_reverse.sh	swahili  --rowlossimportance 10
./study_language_reverse.sh	swedish  --rowlossimportance 10
./study_language_reverse.sh	tagalog  --rowlossimportance 10
./study_language_reverse.sh	tamil  --rowlossimportance 10
./study_language_reverse.sh	tatar  --rowlossimportance 10
./study_language_reverse.sh	telugu  --rowlossimportance 10
./study_language_reverse.sh	thai  --rowlossimportance 10
./study_language_reverse.sh	tibetan -padspace  --rowlossimportance 10
./study_language_reverse.sh	turkish  --rowlossimportance 10
./study_language_reverse.sh	turkmen  --rowlossimportance 10
./study_language_reverse.sh	ukrainian  --rowlossimportance 10
./study_language_reverse.sh	urdu  --rowlossimportance 10
./study_language_reverse.sh	uyghur  --rowlossimportance 10
./study_language_reverse.sh	uzbek  --rowlossimportance 10
./study_language_reverse.sh	yoruba  --rowlossimportance 10
./study_language_reverse.sh	zulu  --rowlossimportance 10
./study_language_reverse.sh	bengali/dhaka  --rowlossimportance 10
./study_language_reverse.sh	bengali/rahr  --rowlossimportance 10
./study_language_reverse.sh	chinese/mandarin -padspace  --rowlossimportance 10
./study_language_reverse.sh	english/american  --rowlossimportance 10
./study_language_reverse.sh	english/british  --rowlossimportance 10
./study_language_reverse.sh	gaelic/irish  --rowlossimportance 10
./study_language_reverse.sh	gaelic/scottish  --rowlossimportance 10
./study_language_reverse.sh	khmer/central  --rowlossimportance 10
./study_language_reverse.sh	latin/classical  --rowlossimportance 10
./study_language_reverse.sh	latin/ecclesiastical  --rowlossimportance 10
./study_language_reverse.sh	malay/arab  --rowlossimportance 8
./study_language_reverse.sh	malay/latin  --rowlossimportance 6
./study_language_reverse.sh	minnan/hokkien2 -padspace  --rowlossimportance 10
./study_language_reverse.sh	minnan/taiwanese2 -padspace  --rowlossimportance 10
./study_language_reverse.sh	nahuatl/central  --rowlossimportance 10
./study_language_reverse.sh	nahuatl/classical  --rowlossimportance 10
./study_language_reverse.sh	nahuatl/mecayapan  --rowlossimportance 10
./study_language_reverse.sh	nahuatl/tetelcingo  --rowlossimportance 10
./study_language_reverse.sh	vietnamese/central  --rowlossimportance 10
./study_language_reverse.sh	vietnamese/northern  --rowlossimportance 10
./study_language_reverse.sh	vietnamese/southern  --rowlossimportance 10
./study_language_reverse.sh	welsh/north  --rowlossimportance 10
./study_language_reverse.sh	welsh/south  --rowlossimportance 10
