#!/bin/bash
 timeout 600 ./study_language.sh	cantonese -padspace
 timeout 600 ./study_language.sh	minnan/hokkien -padspace
 timeout 600 ./study_language.sh	minnan/taiwanese -padspace
 timeout 600 ./study_language.sh	hebrew2		--rowlossimportance 10
exit
 timeout 600 ./study_language.sh	afrikaans	
 timeout 600 ./study_language.sh	albanian	
 timeout 600 ./study_language.sh	amharic	
 timeout 600 ./study_language.sh	arabic	
 timeout 600 ./study_language.sh	aragonese	
 timeout 600 ./study_language.sh	armenian		
 timeout 600 ./study_language.sh	assamese	
 timeout 600 ./study_language.sh	azerbaijani		
 timeout 600 ./study_language.sh	bashkir	
 timeout 600 ./study_language.sh	basque	
 timeout 600 ./study_language.sh	belarusian	
 timeout 600 ./study_language.sh	bengali			
 timeout 600 ./study_language.sh	bengali/dhaka		
 timeout 600 ./study_language.sh	bengali/rahr		
 timeout 600 ./study_language.sh	bishnupriyamanipuri	
 timeout 600 ./study_language.sh	bosnian	
 timeout 600 ./study_language.sh	bulgarian	
 timeout 600 ./study_language.sh	burmese	
 timeout 600 ./study_language.sh	catalan	
 timeout 600 ./study_language.sh	cebuano	
 timeout 600 ./study_language.sh	chechen	
 timeout 600 ./study_language.sh	cherokee	
 timeout 600 ./study_language.sh	chichewa	
 timeout 600 ./study_language.sh	chinese/mandarin	-padspace	 --hyperinit 16  --rowlossimportance 10
 timeout 600 ./study_language.sh	chuvash	
 timeout 600 ./study_language.sh	croatian	
 timeout 600 ./study_language.sh	czech	
 timeout 600 ./study_language.sh	danish	
 timeout 600 ./study_language.sh	dutch	
 timeout 600 ./study_language.sh	dzongkha	
 timeout 600 ./study_language.sh	english	
 timeout 600 ./study_language.sh	esperanto	
 timeout 600 ./study_language.sh	estonian	
 timeout 600 ./study_language.sh	farsi	
 timeout 600 ./study_language.sh	finnish	
 timeout 600 ./study_language.sh	french	
 timeout 600 ./study_language.sh	gaelic/irish	
 timeout 600 ./study_language.sh	gaelic/scottish	
 timeout 600 ./study_language.sh	galician	
 timeout 600 ./study_language.sh	georgian	
 timeout 600 ./study_language.sh	german	
 timeout 600 ./study_language.sh	greek	
 timeout 600 ./study_language.sh	greenlandic	
 timeout 600 ./study_language.sh	guarani	
 timeout 600 ./study_language.sh	gujarati	
 timeout 600 ./study_language.sh	haitiancreole	
 timeout 600 ./study_language.sh	hausa	
 timeout 600 ./study_language.sh	hawaiian	
 timeout 600 ./study_language.sh	hebrew	
 timeout 600 ./study_language.sh	hindi	
 timeout 600 ./study_language.sh	hungarian	
 timeout 600 ./study_language.sh	icelandic	
 timeout 600 ./study_language.sh	ido	
 timeout 600 ./study_language.sh	indonesian	
 timeout 600 ./study_language.sh	interlingua	
 timeout 600 ./study_language.sh	isan	
 timeout 600 ./study_language.sh	italian		--rowlossimportance 6
 timeout 600 ./study_language.sh	jamaican	
 timeout 600 ./study_language.sh	japanese	-padspace --hyperinit 16  --rowlossimportance 10
 timeout 600 ./study_language.sh	javanese	
 timeout 600 ./study_language.sh	kannada	
 timeout 600 ./study_language.sh	kazakh	
 timeout 600 ./study_language.sh	khmer/central	
 timeout 600 ./study_language.sh	kiche	
 timeout 600 ./study_language.sh	konkani	
 timeout 600 ./study_language.sh	korean	
 timeout 600 ./study_language.sh	kurdish	
 timeout 600 ./study_language.sh	kyrgyz	
 timeout 600 ./study_language.sh	langbelta	
 timeout 600 ./study_language.sh	lao	
 timeout 600 ./study_language.sh	latgalian	
 timeout 600 ./study_language.sh	latin/classical	
 timeout 600 ./study_language.sh	latin/ecclesiastical	
 timeout 600 ./study_language.sh	latvian	
 timeout 600 ./study_language.sh	linguafrancanova	
 timeout 600 ./study_language.sh	lithuanian	
 timeout 600 ./study_language.sh	lojban	
 timeout 600 ./study_language.sh	lulesaami	
 timeout 600 ./study_language.sh	luxembourgish	
 timeout 600 ./study_language.sh	macedonian	
 timeout 600 ./study_language.sh	malayalam	
 timeout 600 ./study_language.sh	malay/arab	
 timeout 600 ./study_language.sh	malay/latin	
 timeout 600 ./study_language.sh	maltese	
 timeout 600 ./study_language.sh	maori	
 timeout 600 ./study_language.sh	marathi	
 timeout 600 ./study_language.sh	mongolian	
 timeout 600 ./study_language.sh	nahuatl/central	
 timeout 600 ./study_language.sh	nahuatl/classical	
 timeout 600 ./study_language.sh	nahuatl/mecayapan	
 timeout 600 ./study_language.sh	nahuatl/tetelcingo	
 timeout 600 ./study_language.sh	nepali	
 timeout 600 ./study_language.sh	nogai	
 timeout 600 ./study_language.sh	norwegian	
 timeout 600 ./study_language.sh	oromo	
 timeout 600 ./study_language.sh	papiamento	
 timeout 600 ./study_language.sh	pashto	
 timeout 600 ./study_language.sh	polish	
 timeout 600 ./study_language.sh	portuguese	
 timeout 600 ./study_language.sh	punjabi	
 timeout 600 ./study_language.sh	quechua	
 timeout 600 ./study_language.sh	quenya	
 timeout 600 ./study_language.sh	romanian	
 timeout 600 ./study_language.sh	russian	
 timeout 600 ./study_language.sh	serbian	
 timeout 600 ./study_language.sh	setswana	
 timeout 600 ./study_language.sh	shantaiyai	
 timeout 600 ./study_language.sh	sindarin	
 timeout 600 ./study_language.sh	sindhi	
 timeout 600 ./study_language.sh	sinhala	
 timeout 600 ./study_language.sh	slovak	
 timeout 600 ./study_language.sh	slovenian	
 timeout 600 ./study_language.sh	spanish	
 timeout 600 ./study_language.sh	swahili	
 timeout 600 ./study_language.sh	swedish	
 timeout 600 ./study_language.sh	tagalog	
 timeout 600 ./study_language.sh	tamil		--rowlossimportance 6
 timeout 600 ./study_language.sh	tatar	
 timeout 600 ./study_language.sh	telugu	
 timeout 600 ./study_language.sh	thai	
 timeout 600 ./study_language.sh	tibetan	-padspace  --hyperinit 16
 timeout 600 ./study_language.sh	turkish	
 timeout 600 ./study_language.sh	turkmen	
 timeout 600 ./study_language.sh	ukrainian	
 timeout 600 ./study_language.sh	urdu	
 timeout 600 ./study_language.sh	uyghur	
 timeout 600 ./study_language.sh	uzbek	
 timeout 600 ./study_language.sh	vietnamese/central	
 timeout 600 ./study_language.sh	vietnamese/northern	
 timeout 600 ./study_language.sh	vietnamese/southern	
 timeout 600 ./study_language.sh	welsh/north	
 timeout 600 ./study_language.sh	welsh/south
 timeout 600 ./study_language.sh	yoruba	
 timeout 600 ./study_language.sh	zulu	

