#!/bin/bash

 timeout 600 ./study_language_reverse.sh	afrikaans	
 timeout 600 ./study_language_reverse.sh	amharic	
 timeout 600 ./study_language_reverse.sh	arabic	
 timeout 600 ./study_language_reverse.sh	armenian	
 timeout 600 ./study_language_reverse.sh	azerbaijani	
 timeout 600 ./study_language_reverse.sh	basque	
 timeout 600 ./study_language_reverse.sh	belarusian	
 timeout 600 ./study_language_reverse.sh	bengali		
 timeout 600 ./study_language_reverse.sh	bengali/dhaka	
 timeout 600 ./study_language_reverse.sh	bengali/rahr	
 timeout 600 ./study_language_reverse.sh	bulgarian	
 timeout 600 ./study_language_reverse.sh	burmese	
 timeout 600 ./study_language_reverse.sh	catalan	
 timeout 600 ./study_language_reverse.sh	cebuano	
 timeout 600 ./study_language_reverse.sh	chechen	
 timeout 600 ./study_language_reverse.sh	chichewa	
 timeout 600 ./study_language_reverse.sh	chinese/mandarin	-padspace
 timeout 600 ./study_language_reverse.sh	croatian	
 timeout 600 ./study_language_reverse.sh	czech	
 timeout 600 ./study_language_reverse.sh	danish	
 timeout 600 ./study_language_reverse.sh	dutch	
 timeout 600 ./study_language_reverse.sh	dzongkha	
 timeout 600 ./study_language_reverse.sh	english	
 timeout 600 ./study_language_reverse.sh	esperanto	
 timeout 600 ./study_language_reverse.sh	estonian	
 timeout 600 ./study_language_reverse.sh	farsi	
 timeout 600 ./study_language_reverse.sh	finnish	
 timeout 600 ./study_language_reverse.sh	french	
 timeout 600 ./study_language_reverse.sh	galician	
 timeout 600 ./study_language_reverse.sh	georgian	
 timeout 600 ./study_language_reverse.sh	german
 timeout 600 ./study_language_reverse.sh	greek	
 timeout 600 ./study_language_reverse.sh	gujarati	
 timeout 600 ./study_language_reverse.sh	hausa	
 timeout 600 ./study_language_reverse.sh	hebrew	
 timeout 600 ./study_language_reverse.sh	hindi	
 timeout 600 ./study_language_reverse.sh	hungarian	
 timeout 600 ./study_language_reverse.sh	icelandic	
 timeout 600 ./study_language_reverse.sh	indonesian	
 timeout 600 ./study_language_reverse.sh	isan	
 timeout 600 ./study_language_reverse.sh	italian	
 timeout 600 ./study_language_reverse.sh	jamaican	
 timeout 600 ./study_language_reverse.sh	japanese	-padspace
 timeout 600 ./study_language_reverse.sh	javanese	
 timeout 600 ./study_language_reverse.sh	kazakh	
 timeout 600 ./study_language_reverse.sh	khmer/central	
 timeout 600 ./study_language_reverse.sh	korean	
 timeout 600 ./study_language_reverse.sh	lao	
 timeout 600 ./study_language_reverse.sh	latvian	
 timeout 600 ./study_language_reverse.sh	lithuanian	
 timeout 600 ./study_language_reverse.sh	luxembourgish	
 timeout 600 ./study_language_reverse.sh	macedonian	
 timeout 600 ./study_language_reverse.sh	malay/arab	
 timeout 600 ./study_language_reverse.sh	malay/latin	
 timeout 600 ./study_language_reverse.sh	malayalam	
 timeout 600 ./study_language_reverse.sh	maltese	
 timeout 600 ./study_language_reverse.sh	marathi	
 timeout 600 ./study_language_reverse.sh	mongolian	
 timeout 600 ./study_language_reverse.sh	nepali	
 timeout 600 ./study_language_reverse.sh	norwegian	
 timeout 600 ./study_language_reverse.sh	pashto	
 timeout 600 ./study_language_reverse.sh	polish	
 timeout 600 ./study_language_reverse.sh	portuguese	
 timeout 600 ./study_language_reverse.sh	punjabi	
 timeout 600 ./study_language_reverse.sh	romanian	
 timeout 600 ./study_language_reverse.sh	russian
 timeout 600 ./study_language_reverse.sh	serbian	
 timeout 600 ./study_language_reverse.sh	slovak	
 timeout 600 ./study_language_reverse.sh	spanish
 timeout 600 ./study_language_reverse.sh	swahili
 timeout 600 ./study_language_reverse.sh	swedish	
 timeout 600 ./study_language_reverse.sh	tagalog	
 timeout 600 ./study_language_reverse.sh	tamil	
 timeout 600 ./study_language_reverse.sh	telugu	
 timeout 600 ./study_language_reverse.sh	thai	
 timeout 600 ./study_language_reverse.sh	tibetan	-padspace
 timeout 600 ./study_language_reverse.sh	turkish	
 timeout 600 ./study_language_reverse.sh	ukrainian	
 timeout 600 ./study_language_reverse.sh	urdu	
 timeout 600 ./study_language_reverse.sh	uyghur	
 timeout 600 ./study_language_reverse.sh	vietnamese/central	
 timeout 600 ./study_language_reverse.sh	vietnamese/northern	
 timeout 600 ./study_language_reverse.sh	vietnamese/southern	
 timeout 600 ./study_language_reverse.sh	yoruba	
 timeout 600 ./study_language_reverse.sh	zulu	

