#!/bin/bash

./train_language_reverse.sh	afrikaans --overwrite 
./train_language_reverse.sh	albanian --overwrite 
./train_language_reverse.sh	amharic --overwrite 
./train_language_reverse.sh	arabic --overwrite 
./train_language_reverse.sh	aragonese --overwrite 
./train_language_reverse.sh	armenian --overwrite 
./train_language_reverse.sh	assamese --overwrite 
./train_language_reverse.sh	azerbaijani --overwrite 
./train_language_reverse.sh	bashkir --overwrite 
./train_language_reverse.sh	basque --overwrite 
./train_language_reverse.sh	belarusian --overwrite 
./train_language_reverse.sh	bengali --overwrite 
./train_language_reverse.sh	bishnupriyamanipuri --overwrite 
./train_language_reverse.sh	bosnian --overwrite 
./train_language_reverse.sh	bulgarian --overwrite 
./train_language_reverse.sh	burmese --overwrite 
./train_language_reverse.sh	cantonese  --overwrite 
./train_language_reverse.sh	catalan --overwrite 
./train_language_reverse.sh	cebuano --overwrite 
./train_language_reverse.sh	chechen --overwrite 
./train_language_reverse.sh	cherokee --overwrite 
./train_language_reverse.sh	chichewa --overwrite 
./train_language_reverse.sh	chuvash --overwrite 
./train_language_reverse.sh	croatian --overwrite 
./train_language_reverse.sh	czech --overwrite 
./train_language_reverse.sh	danish --overwrite 
./train_language_reverse.sh	dutch --overwrite 
./train_language_reverse.sh	dzongkha --overwrite 
./train_language_reverse.sh	english --overwrite 
./train_language_reverse.sh	esperanto --overwrite 
./train_language_reverse.sh	estonian --overwrite 
./train_language_reverse.sh	farsi --overwrite 
./train_language_reverse.sh	finnish --overwrite 
./train_language_reverse.sh	french --overwrite 
./train_language_reverse.sh	galician --overwrite 
./train_language_reverse.sh	georgian --overwrite 
./train_language_reverse.sh	german --overwrite 
./train_language_reverse.sh	greek --overwrite 
./train_language_reverse.sh	greenlandic --overwrite 
./train_language_reverse.sh	guarani --overwrite 
./train_language_reverse.sh	gujarati --overwrite 
./train_language_reverse.sh	haitiancreole --overwrite 
./train_language_reverse.sh	hausa --overwrite 
./train_language_reverse.sh	hawaiian --overwrite 
./train_language_reverse.sh	hebrew2 --overwrite 
./train_language_reverse.sh	hebrew3 --overwrite 
./train_language_reverse.sh	hindi --overwrite 
./train_language_reverse.sh	hungarian --overwrite 
./train_language_reverse.sh	icelandic --overwrite 
./train_language_reverse.sh	ido --overwrite 
./train_language_reverse.sh	indonesian --overwrite 
./train_language_reverse.sh	interlingua --overwrite 
./train_language_reverse.sh	isan --overwrite 
./train_language_reverse.sh	italian --overwrite 
./train_language_reverse.sh	jamaican --overwrite 
./train_language_reverse.sh	japanese  --overwrite 
./train_language_reverse.sh	javanese --overwrite 
./train_language_reverse.sh	kannada --overwrite 
./train_language_reverse.sh	kazakh --overwrite 
./train_language_reverse.sh	kiche --overwrite 
./train_language_reverse.sh	konkani --overwrite 
./train_language_reverse.sh	korean --overwrite 
./train_language_reverse.sh	kurdish --overwrite 
./train_language_reverse.sh	kyrgyz --overwrite 
./train_language_reverse.sh	langbelta --overwrite 
./train_language_reverse.sh	lao --overwrite 
./train_language_reverse.sh	latgalian --overwrite 
./train_language_reverse.sh	latvian --overwrite 
./train_language_reverse.sh	linguafrancanova --overwrite 
./train_language_reverse.sh	lithuanian --overwrite 
./train_language_reverse.sh	lojban --overwrite 
./train_language_reverse.sh	lulesaami --overwrite 
./train_language_reverse.sh	luxembourgish --overwrite 
./train_language_reverse.sh	macedonian --overwrite 
./train_language_reverse.sh	malayalam --overwrite 
./train_language_reverse.sh	maltese --overwrite 
./train_language_reverse.sh	maori --overwrite 
./train_language_reverse.sh	marathi --overwrite 
./train_language_reverse.sh	mongolian --overwrite 
./train_language_reverse.sh	nepali --overwrite 
./train_language_reverse.sh	nogai --overwrite 
./train_language_reverse.sh	norwegian --overwrite 
./train_language_reverse.sh	oromo --overwrite 
./train_language_reverse.sh	papiamento --overwrite 
./train_language_reverse.sh	pashto --overwrite 
./train_language_reverse.sh	polish --overwrite 
./train_language_reverse.sh	portuguese --overwrite 
./train_language_reverse.sh	punjabi --overwrite 
./train_language_reverse.sh	quechua --overwrite 
./train_language_reverse.sh	quenya --overwrite 
./train_language_reverse.sh	romanian --overwrite 
./train_language_reverse.sh	russian --overwrite 
./train_language_reverse.sh	serbian --overwrite 
./train_language_reverse.sh	setswana --overwrite 
./train_language_reverse.sh	shantaiyai  --overwrite 
./train_language_reverse.sh	sindarin --overwrite 
./train_language_reverse.sh	sindhi --overwrite 
./train_language_reverse.sh	sinhala --overwrite 
./train_language_reverse.sh	slovak --overwrite 
./train_language_reverse.sh	slovenian --overwrite 
./train_language_reverse.sh	spanish --overwrite 
./train_language_reverse.sh	swahili --overwrite 
./train_language_reverse.sh	swedish --overwrite 
./train_language_reverse.sh	tagalog --overwrite 
./train_language_reverse.sh	tamil --overwrite 
./train_language_reverse.sh	tatar --overwrite 
./train_language_reverse.sh	telugu --overwrite 
./train_language_reverse.sh	thai --overwrite 
./train_language_reverse.sh	tibetan  --overwrite 
./train_language_reverse.sh	turkish --overwrite 
./train_language_reverse.sh	turkmen --overwrite 
./train_language_reverse.sh	ukrainian --overwrite 
./train_language_reverse.sh	urdu --overwrite 
./train_language_reverse.sh	uyghur --overwrite 
./train_language_reverse.sh	uzbek --overwrite 
./train_language_reverse.sh	yoruba --overwrite 
./train_language_reverse.sh	zulu --overwrite 
./train_language_reverse.sh	bengali/dhaka --overwrite 
./train_language_reverse.sh	bengali/rahr --overwrite 
./train_language_reverse.sh	chinese/mandarin  --overwrite 
./train_language_reverse.sh	english/american --overwrite 
./train_language_reverse.sh	english/british --overwrite 
./train_language_reverse.sh	gaelic/irish --overwrite 
./train_language_reverse.sh	gaelic/scottish --overwrite 
./train_language_reverse.sh	khmer/central --overwrite 
./train_language_reverse.sh	latin/classical --overwrite 
./train_language_reverse.sh	latin/ecclesiastical --overwrite 
./train_language_reverse.sh	malay/arab --overwrite 
./train_language_reverse.sh	malay/latin --overwrite 
./train_language_reverse.sh	minnan/hokkien2  --overwrite 
./train_language_reverse.sh	minnan/taiwanese2  --overwrite 
./train_language_reverse.sh	nahuatl/central --overwrite 
./train_language_reverse.sh	nahuatl/classical --overwrite 
./train_language_reverse.sh	nahuatl/mecayapan --overwrite 
./train_language_reverse.sh	nahuatl/tetelcingo --overwrite 
./train_language_reverse.sh	vietnamese/central --overwrite 
./train_language_reverse.sh	vietnamese/northern --overwrite 
./train_language_reverse.sh	vietnamese/southern --overwrite 
./train_language_reverse.sh	welsh/north --overwrite 
./train_language_reverse.sh	welsh/south --overwrite 


