#!/bin/bash

./train_language.sh	afrikaans --overwrite 
./train_language.sh	albanian --overwrite 
./train_language.sh	amharic --overwrite 
./train_language.sh	arabic --overwrite 
./train_language.sh	aragonese --overwrite 
./train_language.sh	armenian --overwrite 
./train_language.sh	assamese --overwrite 
./train_language.sh	azerbaijani --overwrite 
./train_language.sh	bashkir --overwrite 
./train_language.sh	basque --overwrite 
./train_language.sh	belarusian --overwrite 
./train_language.sh	bengali --overwrite 
./train_language.sh	bishnupriyamanipuri --overwrite 
./train_language.sh	bosnian --overwrite 
./train_language.sh	bulgarian --overwrite 
./train_language.sh	burmese --overwrite 
./train_language.sh	cantonese  --overwrite 
./train_language.sh	catalan --overwrite 
./train_language.sh	cebuano --overwrite 
./train_language.sh	chechen --overwrite 
./train_language.sh	cherokee --overwrite 
./train_language.sh	chichewa --overwrite 
./train_language.sh	chuvash --overwrite 
./train_language.sh	croatian --overwrite 
./train_language.sh	czech --overwrite 
./train_language.sh	danish --overwrite 
./train_language.sh	dutch --overwrite 
./train_language.sh	dzongkha --overwrite 
./train_language.sh	english --overwrite 
./train_language.sh	esperanto --overwrite 
./train_language.sh	estonian --overwrite 
./train_language.sh	farsi --overwrite 
./train_language.sh	finnish --overwrite 
./train_language.sh	french --overwrite 
./train_language.sh	galician --overwrite 
./train_language.sh	georgian --overwrite 
./train_language.sh	german --overwrite 
./train_language.sh	greek --overwrite 
./train_language.sh	greenlandic --overwrite 
./train_language.sh	guarani --overwrite 
./train_language.sh	gujarati --overwrite 
./train_language.sh	haitiancreole --overwrite 
./train_language.sh	hausa --overwrite 
./train_language.sh	hawaiian --overwrite 
./train_language.sh	hebrew2 --overwrite 
./train_language.sh	hebrew3 --overwrite 
./train_language.sh	hindi --overwrite 
./train_language.sh	hungarian --overwrite 
./train_language.sh	icelandic --overwrite 
./train_language.sh	ido --overwrite 
./train_language.sh	indonesian --overwrite 
./train_language.sh	interlingua --overwrite 
./train_language.sh	isan --overwrite 
./train_language.sh	italian --overwrite 
./train_language.sh	jamaican --overwrite 
./train_language.sh	japanese  --overwrite 
./train_language.sh	javanese --overwrite 
./train_language.sh	kannada --overwrite 
./train_language.sh	kazakh --overwrite 
./train_language.sh	kiche --overwrite 
./train_language.sh	konkani --overwrite 
./train_language.sh	korean --overwrite 
./train_language.sh	kurdish --overwrite 
./train_language.sh	kyrgyz --overwrite 
./train_language.sh	langbelta --overwrite 
./train_language.sh	lao --overwrite 
./train_language.sh	latgalian --overwrite 
./train_language.sh	latvian --overwrite 
./train_language.sh	linguafrancanova --overwrite 
./train_language.sh	lithuanian --overwrite 
./train_language.sh	lojban --overwrite 
./train_language.sh	lulesaami --overwrite 
./train_language.sh	luxembourgish --overwrite 
./train_language.sh	macedonian --overwrite 
./train_language.sh	malayalam --overwrite 
./train_language.sh	maltese --overwrite 
./train_language.sh	maori --overwrite 
./train_language.sh	marathi --overwrite 
./train_language.sh	mongolian --overwrite 
./train_language.sh	nepali --overwrite 
./train_language.sh	nogai --overwrite 
./train_language.sh	norwegian --overwrite 
./train_language.sh	oromo --overwrite 
./train_language.sh	papiamento --overwrite 
./train_language.sh	pashto --overwrite 
./train_language.sh	polish --overwrite 
./train_language.sh	portuguese --overwrite 
./train_language.sh	punjabi --overwrite 
./train_language.sh	quechua --overwrite 
./train_language.sh	quenya --overwrite 
./train_language.sh	romanian --overwrite 
./train_language.sh	russian --overwrite 
./train_language.sh	serbian --overwrite 
./train_language.sh	setswana --overwrite 
./train_language.sh	shantaiyai  --overwrite 
./train_language.sh	sindarin --overwrite 
./train_language.sh	sindhi --overwrite 
./train_language.sh	sinhala --overwrite 
./train_language.sh	slovak --overwrite 
./train_language.sh	slovenian --overwrite 
./train_language.sh	spanish --overwrite 
./train_language.sh	swahili --overwrite 
./train_language.sh	swedish --overwrite 
./train_language.sh	tagalog --overwrite 
./train_language.sh	tamil --overwrite 
./train_language.sh	tatar --overwrite 
./train_language.sh	telugu --overwrite 
./train_language.sh	thai --overwrite 
./train_language.sh	tibetan  --overwrite 
./train_language.sh	turkish --overwrite 
./train_language.sh	turkmen --overwrite 
./train_language.sh	ukrainian --overwrite 
./train_language.sh	urdu --overwrite 
./train_language.sh	uyghur --overwrite 
./train_language.sh	uzbek --overwrite 
./train_language.sh	yoruba --overwrite 
./train_language.sh	zulu --overwrite 
./train_language.sh	bengali/dhaka --overwrite 
./train_language.sh	bengali/rahr --overwrite 
./train_language.sh	chinese/mandarin  --overwrite 
./train_language.sh	english/american --overwrite 
./train_language.sh	english/british --overwrite 
./train_language.sh	gaelic/irish --overwrite 
./train_language.sh	gaelic/scottish --overwrite 
./train_language.sh	khmer/central --overwrite 
./train_language.sh	latin/classical --overwrite 
./train_language.sh	latin/ecclesiastical --overwrite 
./train_language.sh	malay/arab --overwrite 
./train_language.sh	malay/latin --overwrite 
./train_language.sh	minnan/hokkien2  --overwrite 
./train_language.sh	minnan/taiwanese2  --overwrite 
./train_language.sh	nahuatl/central --overwrite 
./train_language.sh	nahuatl/classical --overwrite 
./train_language.sh	nahuatl/mecayapan --overwrite 
./train_language.sh	nahuatl/tetelcingo --overwrite 
./train_language.sh	vietnamese/central --overwrite 
./train_language.sh	vietnamese/northern --overwrite 
./train_language.sh	vietnamese/southern --overwrite 
./train_language.sh	welsh/north --overwrite 
./train_language.sh	welsh/south --overwrite 


